# Generated by Django 3.1.2 on 2020-11-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('answer_correct', models.BooleanField(default=0)),
                ('answer_fifty_fifty', models.BooleanField(default=0)),
                ('answer_comment', models.CharField(max_length=400)),
                ('answer_picture', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_author', models.CharField(max_length=30)),
                ('question_category', models.CharField(max_length=30)),
            ],
        ),
    ]
