# Generated by Django 3.1.3 on 2020-11-29 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='picture',
            field=models.FileField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='answer',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=models.FileField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quizuser'),
        ),
        migrations.AlterField(
            model_name='quizuser',
            name='email',
            field=models.EmailField(max_length=32),
        ),
        migrations.AlterField(
            model_name='quizuser',
            name='picture',
            field=models.FileField(null=True, upload_to=None),
        ),
    ]
