# Generated by Django 3.1.3 on 2020-11-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201129_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='userId',
            field=models.CharField(max_length=256),
        ),
    ]
