# Generated by Django 3.1.3 on 2020-11-29 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201129_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quizuser'),
        ),
    ]
